name: catopia
description: Cat app
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  bloc: ^8.1.4
  cached_network_image: ^3.4.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  http: ^1.2.2
  infinite_scroll_pagination: ^4.0.0
  intl: ^0.19.0
  loading_animation_widget: ^1.2.1
  meta: ^1.15.0

dev_dependencies:
  bloc_test: ^9.1.7
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/

  fonts:
  - family: Animeace
    fonts:
      - asset: fonts/animeace/animeace_reg.otf
        style: normal
        weight: 400
      - asset: fonts/animeace/animeace_bld.otf
        weight: 700
      - asset: fonts/animeace/animeace_ital.otf
        style: italic
        weight: 400
  - family: Helvetica
    fonts:
      - asset: fonts/helvetica/helvetica_reg.ttf
        style: normal
        weight: 400
      - asset: fonts/helvetica/helvetica_bld.ttf
        weight: 700
